### ISSUE TITLE
有三個問題想匯報一下。

### ISSUE THREAD

**Issue by mikuyourworld** [Elem8100/WzComparerR2-Plus#2]
第一個是，楓之谷DB裡面，選擇技能1从wz读取后，保存bin會出錯，載入bin也會出錯。
第二個是，按照原來的楓谷DB的話，技能1是Skill.wz，技能2是Skill001.wz，技能3是Skill002.wz。但是現在技能1好像是讀取所有skill的wz文件？技能2和技能3好像是一樣的，但是不是所有skill的wz文件。
第二個就是，技能有skill，skill001，skill002，skill003，
請問可以追加一下新的skill003麼！謝謝。

**Comment by Elem8100** [comment]
已修復

**Comment by mikuyourworld** [comment]
原來如此，那更方便了。謝謝！
