### ISSUE TITLE
8/4 KMST DB2 無法正常讀取，Harepacker可以

### ISSUE THREAD

**Issue by FanChihLing** [Elem8100/WzComparerR2-Plus#20]
我從WZ看發現很多部分 例如：Character
每個裝備部位都新增了一個叫做_Canvas的資料夾

報錯大致有兩種

1. 地圖：並未將物件參考設定為物件的執行個體
System.NullReferenceException: 並未將物件參考設定為物件的執行個體。
   於 WzComparerR2.Common.Wz_NodeExtension2.ImgID(Wz_Node Node)
   於 WinFormsApp1.DB2Form.LoadMap(Int32 Part)
   於 System.Windows.Forms.Control.OnClick(EventArgs e)
   於 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   於 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   於 System.Windows.Forms.Control.WndProc(Message& m)
   於 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   於 System.Windows.Forms.Button.WndProc(Message& m)
   於 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

******************************************************************************************************************

2. 消耗：輸入字串格式不正確
System.FormatException: 輸入字串格式不正確。
   於 System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   於 System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   於 WinFormsApp1.DB2Form.LoadItem()
   於 System.Windows.Forms.Control.OnClick(EventArgs e)
   於 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   於 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   於 System.Windows.Forms.Control.WndProc(Message& m)
   於 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   於 System.Windows.Forms.Button.WndProc(Message& m)
   於 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Elem8100** [comment]
我沒裝KMST目前無法測試

**Comment by FanChihLing** [comment]
馬上購買100GB 容量
壓縮上傳來支援您囉 <3
https://1drv.ms/u/s!Auti_lzMVuzCgTM62cajxf4wUgsB?e=wkelo6

**Comment by Elem8100** [comment]
謝了! 已全部修復，如有問題再回報

**Comment by FanChihLing** [comment]
他看起來是把outlink的圖片全部移動到_Canva裡面了
不確定這樣子
對於檔案縮小有沒有沒幫助

目前還有一個問題是紙娃娃沒辦法顯示

**Comment by Elem8100** [comment]
圖片移動到_Canva裡的用意並不是要縮小檔案
因為楓谷數據與資料太多太雜  
將資料圖片分類歸位, 方便管理或更新維護

紙娃娃沒顯示問題已修復
