### ISSUE TITLE
希望能增加顯示大師標籤武器的殘留特效

### ISSUE THREAD

**Issue by u1nnn3** [Elem8100/WzComparerR2-Plus#21]
您好，介面和功能很好用，非常喜歡!
但有幾個功能希望有機會能增加
1.大師標籤武器的殘留特效的模擬和顯示
2.下載gif檔會有髒髒的底色，例如在白底以外的底色會看到，變成需要一個一個影格的圖下載和自己組裝，想下載apng的確會是單一個影格無法是動態的，不曉得有沒有什麼辦法可以解決此問題?
3.希望能增加髮型和臉型的混染功能

**Comment by Elem8100** [comment]
我這Plus版只是追加DB2及圖片瀏覽功能
至於你說的那3種功能要問原創作者才有辦法
https://github.com/Kagamia/WzComparerR2

**Comment by u1nnn3** [comment]
原來是這樣，感謝您
