### ISSUE TITLE
你好方便告知如何破解游戏文件的思路吗？

### ISSUE THREAD

**Issue by flc1125** [Elem8100/WzComparerR2-Plus#23]

**Comment by flc1125** [comment]
@Elem8100

**Comment by Elem8100** [comment]
Wz解析庫不是我寫的，你要問原創作者
https://github.com/Kagamia/WzComparerR2

**Comment by flc1125** [comment]
> Wz解析庫不是我寫的，你要問原創作者
> 
> https://github.com/Kagamia/WzComparerR2

谢谢
