### ISSUE TITLE
關於內建的DB2

### ISSUE THREAD

**Issue by FanChihLing** [Elem8100/WzComparerR2-Plus#7]
請問內建的DB2
有沒有可能可以新增複製內容的功能呢?

**Comment by Elem8100** [comment]
不太懂你的意思, 按滑鼠右鍵本來就有copy的功能不是嗎?
![Image 3](https://user-images.githubusercontent.com/49195287/179736058-4c161b31-cbb0-40dc-ae6e-4a168bda0927.jpg)

**Comment by FanChihLing** [comment]
哦!
抱歉，對不起。
因為我舊版獨立的DB2都用ctrl + c，
原來內建的要用又見copy。
謝謝。
